### ISSUE TITLE
Initializing database issue  preview installation 

### ISSUE THREAD

**Issue by m4bulmagd** [voicelab-org/labelit#56]
- :~/code/labelit_install/labelit$ docker compose -f $DOCKERFILE exec backend bash -c "python manage.py migrate && python manage.py create_initial_users_if_do_not_exist"
    [CRITICAL:2023-01-17 03:09:29.481] Uncaught exception: <class 'django.db.utils.OperationalError'> could not translate host name "postgres" to address: Temporary failure in name resolution
    [log.py:11,uncaught_exception_handler()]
    
    

abelit-postgres-1  | 2023-01-17 03:16:29.413 UTC [1] FATAL:  database files are incompatible with server
labelit-postgres-1  | 2023-01-17 03:16:29.413 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 15.1.

**Comment by m4bulmagd** [comment]
issue fixed by    changing the docker file 
services:
-  from image: postgres:15-alpine
- to :  image: postgres:10-alpine

**Comment by corentingiraud** [comment]
In production, we use Postgres v15. The solution would be to remove the docker volume and to start a database from scratch.
Closing.
