### ISSUE TITLE
minio issue 

### ISSUE THREAD

**Issue by m4bulmagd** [voicelab-org/labelit#57]
- labelit-minio-1     | ERROR Unable to use the drive /export: Drive /export: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified

**Comment by m4bulmagd** [comment]
fix by downgrade mino to lower version eg:
minio/minio:RELEASE.2022-10-24T18-35-07Z.hotfix.ce525fdaf

i think its okay to downgrade as its only used for local testing and there is no much to get from upgrading

**Comment by corentingiraud** [comment]
Same as #56. I prefer to use the latest version even if we must start from scratch.
